### ISSUE TITLE
Can you say something in FAQ about campatability with older 32-bit mac pro hardware?

### ISSUE THREAD

**Issue by djangofan** [ITzTravelInTime/TINU#1]
Can you say something in FAQ about older 32-bit mac pro hardware?  Will it work or is TINU exclusively 64-bit?

**Comment by ITzTravelInTime** [comment]
Tinu is made in swift 3, so it is limited to support only 64 bit hardware and mac os versions starting from yosemite, that's a limitation of swift which does not allows to complice code in 32 bit for mac apps, and also the yosemite requrement is here because some fetures of cocoa which i need have been added in yosemite

**Comment by ITzTravelInTime** [comment]
I have also added this information to the wiki
