### ISSUE TITLE
Please add an OpenCore EFI folder option

### ISSUE THREAD

**Issue by chriswayg** [ITzTravelInTime/TINU#11]
It would really be nice to add the OpenCore EFI folder in the same way as adding a Clover EFI folder. 

Is there actually a difference, or will your tool accept any EFI folder including the OpenCore one? (If thats the case, maybe just add that to the text in the dialog box.)

**Comment by ITzTravelInTime** [comment]
It's being added, be patient for some days, but it's almost ready to be tested

**Comment by ITzTravelInTime** [comment]
Option added, it will be there with TINU 3.0 beta 2

**Comment by chriswayg** [comment]
One thing I noticed when letting TINU add the OpenCore EFI folder is that it will ask for an admin password multiple times. Could you cache the privilege escalation for 15 minutes, similar to sudo, so that the password needs to be entered only once? 

This caching would also be useful for the EFI Partition Mounter, when mounting multiple EFIs. (Hackintool has implemented this for its built-in EFI mounter.)

(using  in TINU 3.0 beta 2 on Mojave)

**Comment by ITzTravelInTime** [comment]
It's not possible, becuase the system which allows for administrator stuff had to be implemented in a particular way, normally a special kind ok program embendeed in the app is needed, this programrequires the usage of a very complex structure and of a developer apple account, i attempted many times at creating an authentication system the normal way but failed for multiple reasons, so i made something based on apple scripts which allows to have all the administrator operations i need with a little code and no apple developer subscription, the olnly problem is that each administrator operation essentially is it's own program and that doesn't allow for one authorization. Another problem is that the documentation for then administrator stuff is really ancient and has not been upodated since 2012-2013 and it's objective c only while i need swift. So for several problems i had i decided for an easyer solution to implement becuase honestly it's huge effort to implement the proper way of having administrator priviladges and it isn't worth it, at least if apple doesn't find a simpler way or provvides updated documentation or a simpler way.

That said, what are you trying out is the the beta 2, is more a work in progress version of it, still missing a few things.

**Comment by chriswayg** [comment]
I get about 3 authorization prompts even on 3.0 beta 1. 

>  it's objective c only while i need swift.

Ok, I see the problem. - I sometimes use the EFI mounter from [Hackintool](https://www.insanelymac.com/forum/topic/335018-hackintool-v286/) which actually caches credentials for a few minutes. It's the only EFI mounter tool that does it, which is quite handy when copying from one EFI to another.

You can try it out and also find the `Authorization` source code [here](https://github.com/headkaze/Hackintool/blob/8bf28d5c21208a446a684f13c8a1d3bc5bcb7644/Hackintool/Authorization.m), but it is Objective C. I don't know, if this code is easily applicable or transferable to Swift.

**Comment by ITzTravelInTime** [comment]
More or less addressed with the latest release: https://github.com/ITzTravelInTime/TINU/releases/tag/3.0_BETA_3_(70)
