### ISSUE TITLE
TINU on Mojave fails to download Sierra & El Capitan 

### ISSUE THREAD

**Issue by chriswayg** [ITzTravelInTime/TINU#13]
On macOS 10.14.5 with TINU 3.0 beta 1 it will not show Catalina as an Option to download. When I search on the App Store or look in Software Update directly, it will show Catalina. I also had it refuse to download macOS versions multiple times: "The requested version of macOS is not available". This occurred with Mojave twice (then it finally worked), Sierra & El Capitan fails always. It's obviously not the fault of TINU, but it shows that using App Store links may not be a reliable way of getting macOS.

Could you provide additional _alternate_ direct download links similar to what these tools are doing? [dosdude1](http://dosdude1.com/software.html)  or [gibMacOS](https://github.com/corpnewt/gibMacOS)

![image](https://user-images.githubusercontent.com/13681327/71346314-98666b00-25a2-11ea-8a66-e0bf65f8cd6d.png)

![image](https://user-images.githubusercontent.com/13681327/71345301-f0e83900-259f-11ea-9bef-5b495e5ca7b2.png)

**Comment by ITzTravelInTime** [comment]
the catalina link has already been added and it will be usable for beta 2 and the fact that fails it's not tinu's fault but it's a fault of the app store and apple, tinu to stay legal just porvvides links for the official downloads, third party downloads are not linked because of possible legal issues, tinu is intended to stay legal

**Comment by chriswayg** [comment]
It's good to offer the App store download links as they work for some versions. But the downloaders I mention also download directly from the Apple servers. For example the [dosdude1 Mojave installer](http://dosdude1.com/mojave/) is actually intended to be used on real Macs (like my MacBook Pro 2010) which would otherwise refuse to install Mojave. Thus I do not think there is any concern from Apple. I was **not** suggesting to offer third party ('pirated') download links for macOS from Bittorrent or elsewhere, just direct download links from Apple servers. 

dosdude1 and gibMacOS use such links from Apple servers.

**Comment by ITzTravelInTime** [comment]
Yes, i know all of those, but i mean that those are not inteded ways by apple themselfs, apple wants you to use the appstore or just downloads on their website for things like updates and patches, and by using those you also have to agree to some EULAs by apple. 

I just want the tool to be an all original thing.

But i have to specify that you are perfectly free to get the installer app from whatever place you want as long as it's equivalent to the app store one (or otherwise the tool will not work), and i just don't want to have the responsibility to link users to third party methods, whaterver they are, and so not having situations like them complain back to me for those methods i linked for example, so i just link them all the official ways and then it's up to them to find a way which works if the official ones don't, it's really outside of the scope of the tool to provvide a way to get the installer app, since it's assumed as a requirement.

**Comment by chriswayg** [comment]
> i just don't want to have the responsibility to link users to third party methods, whaterver they are, and so not having situations like them complain back to me for those methods i linked for example

Yeah sure, it's probably best to keep TINU as focussed and lean as possible, preventing maintenance hassles in the future.

Catalina now shows up and works in beta 2. - As for the App store links, I suspect that macOS Sierra & El Capitan have actually been removed, because they do not receive security updates any more (Apple only supports 3 versions at the same time). You can still see the App store page, but you cannot download them any more. I now checked multiple times on different installations. - Could you please confirm that?

![image](https://user-images.githubusercontent.com/13681327/71435608-ae039e00-2724-11ea-8f8f-cdac417cc4e1.png)

**Comment by chriswayg** [comment]
Its actually even more complicated: A lot of problems relating to downloading macOS  have been covered in this article: [How to download macOS Catalina, Mojave or High Sierra Full Installers](https://mrmacintosh.com/how-to-download-macos-catalina-mojave-or-high-sierra-full-installers/)

**Apple provides the direct download links instead of the App store links in its own documentation, because they are less troublesome.**

[How to upgrade to macOS Sierra - Apple Support](https://support.apple.com/en-us/HT208202)
Direct download link: [Download macOS Sierra](http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg) 

[How to upgrade to OS X El Capitan - Apple Support](https://support.apple.com/en-us/HT206886)
Direct download link: [Download OS X El Capitan](http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg)

**Comment by ITzTravelInTime** [comment]
Yes' that's what i have decided to do, but i will also rework the downloads windows to let it be programmatic instead of hard coded as it is now, but this is not a thing of priority now

**Comment by ITzTravelInTime** [comment]
This has finally been addressed with the new release https://github.com/ITzTravelInTime/TINU/releases/tag/3.0_BETA_3_(70)
