### ISSUE TITLE
Stuck on Set progress value 1005.0

### ISSUE THREAD

**Issue by hasrt1206** [ITzTravelInTime/TINU#17]
I have been stuck on Set progress value 1005.0 for hours. The "completion" bar was done like an hour ago.
Here is a screenshot: https://imgur.com/a/9DySgTe

**Comment by ITzTravelInTime** [comment]
First of all i need more info, like the precise version you were using, info about your usb drive and the drive in which you had your macOS installer app on.

Then i think that your problem may be caused by one of those 2 things:
1) A bug in detecting the end of the createinstallmedia process
2) The createinstallmedia process for some reason was still active

In the first case i have already reworked all the progressbar and detection code as a preparation for version 3.0 BETA 4, so it will likely fix all of this if that's the case. In the second case the problem is with the apple's executable tinu uses, and that may be caused by a problem with your copy of the macOS installer app or your machine, like your drives being too slow, for example on some machines (like my base model 2014 mac mini with a slow 5400 rmp hard drive) the installer creation can take like 80 minutes with the latest betas of big sur which are over 12gb in size.

In any case i reccommend you to have the installer app on an ssd, having a known good and fast usb drive and using the latest beta version of tinu available, if you still have problems i think that you should use another computer, another macOS installation or the terminal method. 

I will release TINU 3.0 BETA 4 when i will have finished with some redesign jobs and worked out the main bugs, so you will be also able to try that.

**Comment by ITzTravelInTime** [comment]
Just as an update, have you tried the new TINU 3.0 BETA 4?

https://github.com/ITzTravelInTime/TINU/releases/tag/3.0_BETA_4_(82)

**Comment by ITzTravelInTime** [comment]
The progress bar system has been overhauled with the latest release (3.0 release candidate) and so the likely cause of this bug has been fixed.
