### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by skwiz0d** [ITzTravelInTime/TINU#19]
I really love the concept of this app.  One thing I noticed while testing is if you have many drives, the app doesnt resize and show all of the them.  It cuts off like 4 and a half wide.
![Screen Shot 2021-10-29 at 9 32 50 AM](https://user-images.githubusercontent.com/62028104/139444139-e76a1069-a4bc-4b45-853e-8383b7c3fda9.png)

**Comment by ITzTravelInTime** [comment]
Hi, the problem you see is that macOS for some reason hides the scroll bar from you, in fact normally you should see a scroll bar that allows you should see a scroll bar at the bottom like in this picture. This can be caused by the fact you have some touch enabled pointing device (mouse or trackpad), so in that case you should try to scroll sideways if you can or you should disconnect that pointing device. 

This is mostly a macOS bug and not really TINU's fault, but i am at work trying to improve this situation.


![Schermata 2021-10-29 alle 19 36 20](https://user-images.githubusercontent.com/23339020/139478577-6ed8fd9d-bd98-4772-a0b4-f84b9669a999.png)

**Comment by skwiz0d** [comment]
ahhh, ok.  yeah this was on a desktop with a mouse.  I thought this may be the case, but I couldn't get it do budge.  Anyway, I appreciate the info!  Great tool btw.  Used it twice already so thank you.

**Comment by ITzTravelInTime** [comment]
Last thing i want to say is that i am looking for some way to let the view scroll horizzontally when you use a regular desktop mouse's scroll wheel.

Anyway thank you for appreciating the app.

**Comment by ITzTravelInTime** [comment]
So, @skwiz0d  even i haven't figure out the scroll bar visibility (yet) i have to tell you that i have successfully managed to let the mouse scroll wheel scroll horizontally instead of vertically for that screen and the installer app select screen. So in the upcoming version 3.0.1 this will be at least addressed in some way. About resizing the window layout i am currently using doesn't really allows that, but it's not a bad idea, i will keep it in consideration for an eventual future release if i manage to let it work.
