### ISSUE TITLE
Every time you open the terminal and enter the password, have you considered using the privileged assistant? In this way, you don't have to open the terminal every time. This is very helpful for user interaction!

### ISSUE THREAD

**Issue by DevLiuSir** [ITzTravelInTime/TINU#24]
First of all. Thank you for your tool program. It's great. However, every time you open the terminal and enter the password, it will make others feel bored over time. Have you considered using the privileged assistant? In this way, you don't have to open the terminal every time. This is very helpful for user interaction!

**Comment by ITzTravelInTime** [comment]
This was considered basically sinc eday one, but had to be avoided for a few reasons, mainly: 

1) Setting it up and reproducing it requires a paid developer subscription and signing certificates, and that alone goes well against the principles of this open source software, which has the objective of being freely usable and re-compilable by anyone without any extra stuff.

2) on modern macOS `createinstallmedia` (which is really what does the heavy lifting here) requires some special permits that only a few apps can give, such as the system terminal, so that's why I have to use it in the stack, but it isn't used when you run tinu on older system versions. With some setup and using a privileged assistant it should be possible to get to the required privilege level just by this app alone in theory, but again, setting all of this up really defeats the open nature of the tool due to the above-mentioned requirements.

That said, I have also been thinking about making a complete reboot of the project and wiring the whole software stack from scratch and perhaps also figuring this stuff out better, I would love to separate the whole software even further into components with this rewrite and also perhaps have a standard backend interface to allow the use of both the current approach and the privileged assistant one with the same code above them (something not possible with the current stack, which is also very messy and doesn't follow proper software design principles I might say, so I feel like a good rewrite might be a good thing).

**Comment by DevLiuSir** [comment]
Thank you for your answer. I understand. Thank you again for your open source so that more people can reconstruct it.

**Comment by DevLiuSir** [comment]
Thank you for your answer. I understand. Thank you again for your open source so that more people can reconstruct it.
