### ISSUE TITLE
Secondary password prompt is not escaped

### ISSUE THREAD

**Issue by uraki66** [ITzTravelInTime/TINU#5]
I couldn't get past the secondary password prompt. My password has '$$' in it. When I enter the '$$' as  '\\$\\$' the secondary password prompt accepts my password. Please escape special characters from secondary password prompt.

**Comment by ITzTravelInTime** [comment]
Yes, i already know about that and this prompt also soffers from other issues, but luckly for the upcoming version i have changed the system that manages the password prompt, and now the app does no longer uses the useres credetials with a sudo command, it instead just uses the system apis via an apple script. So you want you can send me a message on telegram (i use the same nickname as here) and then i will let you join the beta testing group to try the new version, i am still making some modifications for the ui before rolling it out, but the functionality is all there. 

Note that because of some limitations with privilaged tasks with apple scripts, the new system will ask more than 2 times the passowrd, up to 4-5 times depending on which operations the tool needs to make, for example if tinu needs to change the partition method used for the usb drive, it will ask 2 times the password just for this, because it needs to unmount with priviladges the usb drive and then to perform the actual format command.

**Comment by ITzTravelInTime** [comment]
if you want try out the new version in pre-release i can add you to the telegram group, just send me an email with your telegram nickname, so i can add you to the closed group

**Comment by ITzTravelInTime** [comment]
fixed in the new version 2.1, this issue is now closed.
